### ISSUE TITLE
 Enable SkinsRestorerDB in SkinsRestorer config!

### ISSUE THREAD

**Issue by Mitsu13Ion** [riflowth/SkinSystem#78] opened 2019-12-15 21:40 UTC
Hello, i have this error
Enable SkinsRestorerDB in SkinsRestorer config!
MySQL:
  Enabled: true
  Host: ////
  Port: ////
  Database: ////
  Username: ////
  Password: ////
  SkinTable: 'Skins'
  PlayerTable: 'Players'

**Comment by ITZVGcGPmO** [comment] 2019-12-20 06:51
duplicate of #77

**Closed by ITZVGcGPmO** 2019-12-20 06:51 UTC
